name: environment-variables
on: push
env:
  EXAMPLE: Define by workflow level
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: Define by step level
        run: echo "${EXAMPLE}"
      - run: echo ${{toJson(env)}}
