name: environment-variables
on: push
env:
  EXAMPLE: Define by workflow level
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: Define by step level
        run: echo "${EXAMPLE}"
      - name: show-all-env
        env:
          CHECK_CONTEXT_ENV: ${{toJson(env)}}
        run: echo "$CHECK_CONTEXT_ENV"
