name: missing-share-data
on: push
jobs:
  share1:
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT環境変数を設定
        id: source
        run: echo "result=hello" >> "${GITHUB_OUTPUT}"
      - name: 前回のステップで設定したGITHUB_OUTPUT環境変数を使用
        env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"
  share2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RESULT=hello" >> "${GITHUB_ENV}"
      - run: echo "${RESULT}"
