name: status-check-functions
on: push
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      - run: echo echo "Hello"
        if: ${{ failure() }}
  release-build:
    if: ${{ github.actor == 'administrator' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "build release version"
