name: status-check-functions
on: push
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      - run: echo echo "Hello"
        if: ${{ failure() }}
  release-build:
    if: ${{ github.actor == 'nishio-n0522' }}
    runs-on: ubuntu-latest
    steps:
      - name: リリースバージョンをビルド
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
        run: |
          echo "$GITHUB_ACTOR"
          echo "build release version"
