name: test-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check-github-context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
